# These resources exist outside of the main Vimana namespace.
# `GatewayClass` is cluster-scoped.
# https://gateway-api.sigs.k8s.io/api-types/gatewayclass/
kind: GatewayClass
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: envoy-gateway
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  # Associate the gateway class with a custom `EnvoyProxy` config.
  # https://gateway.envoyproxy.io/latest/tasks/operations/customize-envoyproxy/
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: vimana-gateway-config
    namespace: envoy-gateway-system
---
# `EnvoyProxy` is namespace-scoped, but lives in the Envoy Gateway system namespace.
# https://gateway.envoyproxy.io/docs/api/extension_types/#envoyproxy
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: vimana-gateway-config
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        # Specify a static name for the gateway service.
        # https://github.com/envoyproxy/gateway/issues/2141
        patch:
          value:
            metadata:
              name: vimana-gateway
