# Default spec for component resources.

# Unique ID of the domain to which this component belongs.
domainId: ""

# ID of the server to which this component belongs.
serverId: ""

# Version of this component.
version: ""

# Vimana "container" image.
image: ""
