apiVersion: api.vimana.host/v1alpha1
kind: Domain
metadata:
  labels:
    app.kubernetes.io/name: vimana-operator
    app.kubernetes.io/managed-by: kustomize
  name: domain-sample
spec:
  # TODO(user): Add fields here
