## Append samples of your project ##
resources:
- api_v1alpha1_vimana.yaml
- api_v1alpha1_domain.yaml
- api_v1alpha1_server.yaml
- api_v1alpha1_component.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
