kind: Deployment
apiVersion: apps/v1
metadata:
  name: d-78c895e3c4aa28e1516b348cc497dc620d30f6753c3298b0d1c2ae04
  labels:
    vimana.host/domain: {{ quote .Values.domainId  }}
    vimana.host/server: {{ quote .Values.serverId  }}
    vimana.host/version: {{ quote .Values.version  }}
spec:
  replicas: 1
  selector:
    matchLabels:
      vimana.host/domain: {{ quote .Values.domainId  }}
      vimana.host/server: {{ quote .Values.serverId  }}
      vimana.host/version: {{ quote .Values.version  }}
  template:
    metadata:
      labels:
        vimana.host/domain: {{ quote .Values.domainId  }}
        vimana.host/server: {{ quote .Values.serverId  }}
        vimana.host/version: {{ quote .Values.version  }}
    spec:
      runtimeClassName: workd-runtime
      serviceAccountName: ''{{/* TODO: Is this necessary? */}}
      containers:
      - name: grpc
        image: {{ printf "%s/%s/%s:%s" (lookup "api.vimana.host/v1alpha1" "Vimana" .Release.Namespace "vimana").spec.registry .Values.domainId .Values.serverId .Values.version }}
        env: []
        imagePullPolicy: Always{{/* TODO: This is necessary for bootstrapped resources (for local testing), but not "normal" resources */}}
