# This rule is not used by the project vimana-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the api.vimana.host.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: vimana-operator
    app.kubernetes.io/managed-by: kustomize
  name: component-editor-role
rules:
- apiGroups:
  - api.vimana.host
  resources:
  - components
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.vimana.host
  resources:
  - components/status
  verbs:
  - get
