# permissions for end users to edit vimanas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: vimana-operator
    app.kubernetes.io/managed-by: kustomize
  name: vimana-editor-role
rules:
- apiGroups:
  - api.vimana.host
  resources:
  - vimanas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.vimana.host
  resources:
  - vimanas/status
  verbs:
  - get
