# Default spec for the vimana resources.

# This is a "singleton" resource.
# Exactly one should exist in any given namespace.
# The existence of the Vimana resource indicates to the operator
# to create pan-cluster resources
# such as the gateway and runtime class used by all Vimana services / components.

# Hostname and optional port of the image registry
# used for all component images within this Vimana.
registry: ""
