{{ $domainId := .Values.id -}}
kind: GRPCRoute
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: {{ $domainId | quote }}
  labels:
    vimana.host/domain: {{ $domainId | quote }}
spec:
  parentRefs:
    - name: vimana-gateway
  hostnames:
    - {{ printf "%s.app.vimana.host" $domainId | quote }}
{{- range .Values.aliases }}
    - {{ . | quote }}
{{- end }}
  rules:
{{- range (lookup "api.vimana.host/v1alpha1" "Server" .Release.Namespace "").items }}
{{- if (eq (get .metadata.labels "vimana.host/domain") $domainId) }}
{{- $serverId := .spec.id }}
    - matches:
{{- range .spec.services }}
        - method:
            service: {{ . | quote }}
            type: Exact
{{- end }}
      backendRefs:
{{- range $version, $weight := .spec.versionWeights }}
        - name: {{ printf "s-%s" (sha256sum (printf "%s:%s@%s" $domainId $serverId $version) | substr 0 48) | quote }}
          kind: Service
          port: 80
          weight: {{ $weight }}
{{- end }}
{{- end }}
{{- end }}
