name: Unit Tests
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # https://github.com/actions/cache/blob/v4.2.3/examples.md#---bazel
      - name: Cache Bazel
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelrc', 'MODULE.bazel') }}
          path: |
            ~/.cache/bazel
          restore-keys: |
            ${{ runner.os }}-bazel-
      - name: Run Tests
        run: |
          # Import deploy keys necessary to download modules from private repo(s)
          # during the build.
          eval "$(ssh-agent -s)"
          <<< '${{ secrets.RULES_K8S_DEPLOY_KEY }}' ssh-add -

          # Run all tests except for the ones located under `e2e/`
          bazel test //... -- -//e2e/...
      - name: Upload Log
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: bazel-testlogs
          path: bazel-testlogs/
