name: Unit Tests
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # https://github.com/actions/cache/blob/v4.2.3/examples.md#---bazel
      - name: Cache Bazel
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelrc', 'MODULE.bazel') }}
          path: |
            ~/.cache/bazel
          restore-keys: |
            ${{ runner.os }}-bazel-
      - name: Run Tests
        id: run-tests
        run: |
          # Import deploy keys necessary to download modules from private repo(s)
          # during the build.
          eval "$(ssh-agent -s)"
          <<< '${{ secrets.RULES_K8S_DEPLOY_KEY }}' ssh-add -

          # Store the absolute path to the Bazel testlogs as an output parameter
          # so it can be uploaded as an artifact in case of failure.
          echo "bazel-testlogs=$(bazel info bazel-testlogs)" >> "$GITHUB_OUTPUT"

          # Run all tests except for the ones located under `e2e/`.
          bazel test //... -- -//e2e/...
      - name: Upload Log
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: bazel-testlogs
          path: ${{ steps.run-tests.outputs.bazel-testlogs }}
