name: Unit Tests
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    # The tests under `//work/runtime/tests` use Bazel's `requires-fakeroot` tag,
    # which enables them to manage IP addresses on the loopback network device.
    # That tag is only available for `linux-sandbox`:
    # https://bazel.build/reference/be/common-definitions#common-attributes.
    # However, GitHub Actions normally run in a VM,
    # and Bazel falls back on the simpler `processwrapper-sandbox` in that environment:
    # https://bazel.build/docs/sandboxing#sandboxing-strategies.
    # That means the tests will not run with root privileges
    # and will be unable to manage IP addresses.
    #
    # Work around this by running in a container with explicit `NET_ADMIN` privileges.
    container:
      image: debian:stable-slim
      options: --cap-add=NET_ADMIN
    # Running inside a container uses the Bourne shell be default. Use Bash instead.
    defaults:
      run:
        shell: bash
    steps:
      - name: Set up environment
        run: |
          # Install basic dependencies.
          apt update
          apt install -y curl jq openssh-client git gcc g++ python3 iproute2

          # Install the latest release of Bazelisk from GitHub.
          LATEST_BAZELISK="$(
            curl --silent --show-error https://api.github.com/repos/bazelbuild/bazelisk/releases/latest \
              | jq --raw-output '.tag_name'
          )"
          curl --silent --show-error --location --remote-name \
            "https://github.com/bazelbuild/bazelisk/releases/download/${LATEST_BAZELISK}/bazelisk-amd64.deb"
          dpkg --install bazelisk-amd64.deb

          # Import GitHub's SSH pubkey securely using the API, for use by Git.
          mkdir --parents "${HOME}/.ssh"
          echo "github.com $(
            curl --silent --show-error https://api.github.com/meta \
              | jq --raw-output 'first(.ssh_keys[] | select(startswith("ssh-rsa")))'
          )" >> "${HOME}/.ssh/known_hosts"
          git config --global core.sshCommand "ssh -o UserKnownHostsFile=${HOME}/.ssh/known_hosts"

          # Import deploy key(s) necessary to download modules from private repo(s) during the build.
          # Export the SSH agent environment variables to be picked up by subsequent steps.
          eval "$(ssh-agent -s)"
          <<< '${{ secrets.RULES_K8S_DEPLOY_KEY }}' ssh-add -
          echo "SSH_AUTH_SOCK=${SSH_AUTH_SOCK}" >> "$GITHUB_ENV"
          echo "SSH_AGENT_PID=${SSH_AGENT_PID}" >> "$GITHUB_ENV"

      - name: Check out repository
        uses: actions/checkout@v4

      # https://github.com/actions/cache/blob/v4.2.3/examples.md#---bazel
      - name: Restore Bazel cache
        id: restore-bazel-cache
        uses: actions/cache/restore@v4
        with:
          key: bazel-cache-${{ hashFiles('.bazelversion', '.bazelrc', 'MODULE.bazel') }}
          path: |
            ~/.cache/bazel
          restore-keys: |
            bazel-cache-

      - name: Build everything
        run: |
          # TODO: Change this to build `//...` once mature.
          bazel build //work/runtime

      - name: Save Bazel cache
        uses: actions/cache/save@v4
        with:
          key: ${{ steps.restore-bazel-cache.outputs.cache-primary-key }}
          path: |
            ~/.cache/bazel

      - name: Run tests
        id: run-tests
        run: |
          # Store the absolute path to the Bazel testlogs as an output parameter
          # so it can be uploaded as an artifact in case of failure.
          echo "bazel-testlogs=$(bazel info bazel-testlogs)" >> "$GITHUB_OUTPUT"

          # Run all tests except for the ones located under `e2e/`.
          # TODO: Un-disable tests under `//api` once mature.
          bazel test --cache_test_results=no //... -- -//e2e/... -//api/...

      - name: Upload test logs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: bazel-testlogs
          path: ${{ steps.run-tests.outputs.bazel-testlogs }}
